<?php
//
// File generated by ... on the 2026-08-21T12:51:13+0300
// Please do not edit manually
//

/**
 * Classes and menus for itop-portal-base (version 3.2.1)
 *
 * @author      iTop compiler
 * @license     http://opensource.org/licenses/AGPL-3.0
 */
const EVENT_DISPLAY_OBJECT_DETAILS = 'EVENT_DISPLAY_OBJECT_DETAILS';
\Combodo\iTop\Service\Events\EventService::RegisterEvent(
  new \Combodo\iTop\Service\Events\Description\EventDescription(
    'EVENT_DISPLAY_OBJECT_DETAILS',
    [
        'cmdbAbstractObject' => 'cmdbAbstractObject',
    ],
    'An object details is about to be displayed to a user on a portal',
    '',
    [
    ],
    'itop-portal-base'
  )
);

