<?php
//
// File generated by ... on the 2026-08-08T13:02:13+0300
// Please do not edit manually
//

/**
 * Classes and menus for registry-service-menu (version 1.0.1)
 *
 * @author      iTop compiler
 * @license     http://opensource.org/licenses/AGPL-3.0
 */

//
// Menus
//
class MenuCreation_registry_service_menu extends ModuleHandlerAPI
{
	public static function OnMenuCreation()
	{
		global $__comp_menus__; // ensure that the global variable is indeed global !
		$__comp_menus__['RequestManagement'] = new MenuGroup('RequestManagement', 30, 'fas fa-comment-alt' , null, UR_ACTION_MODIFY, UR_ALLOWED_YES, null);
		$__comp_menus__['RegistryServiceRequests'] = new OQLMenuNode('RegistryServiceRequests', "SELECT UserRequest AS u JOIN Service AS s ON u.service_id = s.id WHERE s.servicefamily_id = 2", $__comp_menus__['RequestManagement']->GetIndex(), 10, true , null, UR_ACTION_MODIFY, UR_ALLOWED_YES, null, true);
		$__comp_menus__['ICTServiceRequests'] = new OQLMenuNode('ICTServiceRequests', "SELECT UserRequest AS u WHERE (ISNULL(u.service_id)) OR (u.service_id NOT IN (SELECT s FROM Service AS s WHERE s.servicefamily_id = 2))", $__comp_menus__['RequestManagement']->GetIndex(), 11, true , null, UR_ACTION_MODIFY, UR_ALLOWED_YES, null, true);
	}
} // class MenuCreation_registry_service_menu
